// Code generated by Arduino IoT Cloud, DO NOT EDIT.

#include <ArduinoIoTCloud.h>
#include <Arduino_ConnectionHandler.h>

const char SSID[]     = "Galaxy M31s46C5";    // Network SSID (name)
const char PASS[]     = "mgic2858";    // Network password (use for WPA, or use as key for WEP)


String weather_report;
float humidity;
float pressure;
float temperature;
int light;

void initProperties(){

  ArduinoCloud.addProperty(weather_report, READ, ON_CHANGE, NULL);
  ArduinoCloud.addProperty(humidity, READ, 1 * SECONDS, NULL);
  ArduinoCloud.addProperty(pressure, READ, 1 * SECONDS, NULL);
  ArduinoCloud.addProperty(temperature, READ, 1 * SECONDS, NULL);
  ArduinoCloud.addProperty(light, READ, 1 * SECONDS, NULL);

}

WiFiConnectionHandler ArduinoIoTPreferredConnection(SSID, PASS);
